name: Java CI with Maven

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    name: Build jbridge-waterdogpe
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build jbridge-waterdogpe
        run: mvn -pl jbridge-waterdogpe clean install

      - name: Get Maven version
        run: |
          VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ github.workspace }}/jbridge-waterdogpe/target/*.jar
          draft: false
          name: Release v${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "jbridge-waterdogpe artifact built from release branch."
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
